services:
  postgres:
    image: postgres:16
    container_name: securestock-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: migration_dest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cisco
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: securestock-backend
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/migration_dest
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: cisco
    restart: unless-stopped

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: securestock-frontend
    ports:
      - "3000:80"
    depends_on:
      - spring-boot-app
    restart: unless-stopped

volumes:
  postgres_data: